### ISSUE TITLE
error in minfi dmpFinder

### ISSUE THREAD

**Issue by hope2003** [hansenlab/minfi#186] opened 2019-05-23 15:01 UTC
Hi,
 I am having issues with dmpFinder () function. Here is the Error info:
dmp <- dmpFinder(beta, pheno = Sample_Group , type = "categorical") 

Error in smooth.spline(lambda, vec.p0, w = ncs.weights, df = 3) : 
  missing or infinite values in inputs are not allowed
In addition: Warning message:
In pf(Fstat, df1, df2, lower.tail = FALSE) : NaNs produced
How to fix it? Thanks!

**Comment by PeteHaitch** [comment] 2019-05-23 23:41
This is a duplicate of https://support.bioconductor.org/p/121252/
I'll follow up there

**Closed by PeteHaitch** 2019-05-23 23:41 UTC
